/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PostTaskRouteImport } from './routes/post-task'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as IndexRouteImport } from './routes/index'

const PostTaskRoute = PostTaskRouteImport.update({
  id: '/post-task',
  path: '/post-task',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
  id:
    | '__root__'
    | '/'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  JobsRoute: typeof JobsRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRoute
  PostTaskRoute: typeof PostTaskRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/post-task': {
      id: '/post-task'
      path: '/post-task'
      fullPath: '/post-task'
      preLoaderRoute: typeof PostTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  JobsRoute: JobsRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRoute,
  PostTaskRoute: PostTaskRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
