/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PostTaskRouteImport } from './routes/post-task'
import { Route as PassportRouteImport } from './routes/passport'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as JobsRouteImport } from './routes/jobs'
import { Route as CustomerDashboardRouteImport } from './routes/customer-dashboard'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PostTaskRoute = PostTaskRouteImport.update({
  id: '/post-task',
  path: '/post-task',
  getParentRoute: () => rootRouteImport,
} as any)
const PassportRoute = PassportRouteImport.update({
  id: '/passport',
  path: '/passport',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/customer-dashboard',
  path: '/customer-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/customer-dashboard': typeof CustomerDashboardRoute
  '/jobs': typeof JobsRoute
  '/onboarding': typeof OnboardingRoute
  '/passport': typeof PassportRoute
  '/post-task': typeof PostTaskRoute
  '/privacy': typeof PrivacyRoute
  '/profile': typeof ProfileRoute
  '/terms': typeof TermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
    | '/privacy'
    | '/profile'
    | '/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
    | '/privacy'
    | '/profile'
    | '/terms'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/customer-dashboard'
    | '/jobs'
    | '/onboarding'
    | '/passport'
    | '/post-task'
    | '/privacy'
    | '/profile'
    | '/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  JobsRoute: typeof JobsRoute
  OnboardingRoute: typeof OnboardingRoute
  PassportRoute: typeof PassportRoute
  PostTaskRoute: typeof PostTaskRoute
  PrivacyRoute: typeof PrivacyRoute
  ProfileRoute: typeof ProfileRoute
  TermsRoute: typeof TermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-task': {
      id: '/post-task'
      path: '/post-task'
      fullPath: '/post-task'
      preLoaderRoute: typeof PostTaskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passport': {
      id: '/passport'
      path: '/passport'
      fullPath: '/passport'
      preLoaderRoute: typeof PassportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer-dashboard': {
      id: '/customer-dashboard'
      path: '/customer-dashboard'
      fullPath: '/customer-dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  CustomerDashboardRoute: CustomerDashboardRoute,
  JobsRoute: JobsRoute,
  OnboardingRoute: OnboardingRoute,
  PassportRoute: PassportRoute,
  PostTaskRoute: PostTaskRoute,
  PrivacyRoute: PrivacyRoute,
  ProfileRoute: ProfileRoute,
  TermsRoute: TermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
